export { default as HomeStyle } from './HomeStyle';
export { default as AboutStyle } from './AboutStyle';
export { default as SkillStyle } from './SkillStyle.js';
export { default as ExperienceStyle } from './ExperienceStyle';
export { default as EducationStyle } from './EducationStyle';
export { default as WorkStyle } from './WorkStyle';
export { default as ContactStyle } from './ContactStyle';
export { default as SkillsStyle } from './SkillsStyle';
export { default as Workdetails } from './Workdetails';
